name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency: release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Configure git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Bump version
        run: |
          npm version patch
          git push

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Release
        run: |
          npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          DEVFUL_GITHUB_TOKEN: ${{ secrets.DEVFUL_GITHUB_TOKEN }}
